#! /bin/sh
# SPDX-License-Identifier: BSD-2-Clause

# Copyright (C) 2022 Chris Johns (chrisj@rtems.org)
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

set -e
#set -x

if [ $# -eq 0 ]; then
    echo "error: no path to the RTEMS on the command line"
    exit 1
fi

rtems=$1

if [ ! -d ${rtems} ]; then
    echo "error: invalid RTEMS path: ${rtems}"
    exit 1
fi

cfgs=$(find ${rtems} -name \*.cfg -or -name \*.pc -or -name \*.inc)

if [ -z "${cfgs}" ]; then
    echo "error: no target config files found: ${rtems}"
    exit 1
fi

flags="-ffunction-sections -fdata-sections"

count=0
updated=0
for cfg in ${cfgs}
do
    count=$(expr ${count} + 1)
    changed=0
    for flag in ${flags}
    do
        set +e
        grep -q "\\${flag}" ${cfg}
        found=$?
        set -e
        if [ ${found} -eq 0 ]; then
	    changed=1
            cat ${cfg} | sed -e "s/\\${flag}//" > ${cfg}.tmp
            rm ${cfg}
            mv ${cfg}.tmp ${cfg}
            echo "updated: ${cfg}"
        fi
    done
    if [ ${changed} -eq 1 ]; then
	updated=$(expr ${updated} + 1)
    fi
done

echo "${count} configs processed. ${updated} updated"

exit 0
